# Generated by Django 4.1.4 on 2023-03-26 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='finish_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_membership_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='membreship_days',
        ),
        migrations.RemoveField(
            model_name='user',
            name='start_date',
        ),
    ]
