# Generated by Django 4.1.4 on 2023-03-03 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Courses category name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Courses Category slug')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Course Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Course Slug')),
                ('description', models.TextField(blank=True, max_length=450, verbose_name='Brand descrition')),
                ('thumbnail', models.ImageField(default='media/courses/thumbnail/default.jpg', upload_to='media/courses/thumbnail/', verbose_name='Course thumbnail')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/courses/videos/', verbose_name='Course Video')),
                ('video_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Course Video Url')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_user', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_category', to='courses.category')),
            ],
            options={
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_at'],
            },
        ),
    ]
