# Generated by Django 4.1.4 on 2022-12-15 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255, unique=True, verbose_name='Color')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Color slug')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
                ('sku', models.CharField(max_length=20, unique=True, verbose_name='Product sku')),
                ('slug', models.SlugField(max_length=255, verbose_name='Product slug')),
                ('description', models.TextField(blank=True, max_length=455, verbose_name='Product description')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('brand', models.CharField(max_length=255, verbose_name='brand')),
                ('store_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('is_sale_price_active', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('category', models.ManyToManyField(blank=True, related_name='product_categories', to='ecommerce.category')),
                ('colors', models.ManyToManyField(null=True, related_name='item_product_colors', to='ecommerce.color')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media/products/', verbose_name='product image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_media', to='ecommerce.product')),
            ],
            options={
                'verbose_name': 'Product images',
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, unique=True, verbose_name='Size')),
                ('qty', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_size', to='ecommerce.product')),
            ],
            options={
                'verbose_name': 'Sizes',
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.DeleteModel(
            name='Sizes',
        ),
    ]
